use VetNova 
go

CREATE OR ALTER PROCEDURE SP_CONTAR_CITAS
AS BEGIN
	BEGIN TRY
		SELECT COUNT(*) AS Cantidad
		FROM Citas
		WHERE Fecha = CAST(GETDATE() AS DATE)
	END TRY
	BEGIN CATCH
		SELECT -1
	END CATCH
END
GO